/* Automatically generated by po2tbl.sed from enscript.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"%s: option `%s' is ambiguous\n", 2},
  {"%s: option `--%s' doesn't allow an argument\n", 3},
  {"%s: option `%c%s' doesn't allow an argument\n", 4},
  {"%s: option `%s' requires an argument\n", 5},
  {"%s: unrecognized option `--%s'\n", 6},
  {"%s: unrecognized option `%c%s'\n", 7},
  {"%s: illegal option -- %c\n", 8},
  {"%s: invalid option -- %c\n", 9},
  {"%s: option requires an argument -- %c\n", 10},
  {"%s: option `-W %s' is ambiguous\n", 11},
  {"%s: option `-W %s' doesn't allow an argument\n", 12},
  {"xmalloc(): couldn't allocate %d bytes\n", 13},
  {"xcalloc(): couldn't allocate %d bytes\n", 14},
  {"xrealloc(): couldn't reallocate %d bytes\n", 15},
  {"Success", 16},
  {"No match", 17},
  {"Invalid regular expression", 18},
  {"Invalid collation character", 19},
  {"Invalid character class name", 20},
  {"Trailing backslash", 21},
  {"Invalid back reference", 22},
  {"Unmatched [ or [^", 23},
  {"Unmatched ( or \\(", 24},
  {"Unmatched \\{", 25},
  {"Invalid content of \\{\\}", 26},
  {"Invalid range end", 27},
  {"Memory exhausted", 28},
  {"Invalid preceding regular expression", 29},
  {"Premature end of regular expression", 30},
  {"Regular expression too big", 31},
  {"Unmatched ) or \\)", 32},
  {"No previous regular expression", 33},
  {"$3v $-40N $3% pages $4L lines  $E $C", 34},
  {"couldn't get passwd entry for uid=%d: %s", 35},
  {"couldn't open config file \"%s/%s\": %s", 36},
  {"unknown encoding: %s", 37},
  {"couldn't open AFM library: %s", 38},
  {"\
known media:\n\
name             width\theight\tllx\tlly\turx\tury\n\
------------------------------------------------------------\n", 39},
  {"do not know anything about media \"%s\"", 40},
  {"\
set new marginals for media `%s' (%dx%d): llx=%d, lly=%d, urx=%d, ury=%d\n", 41},
  {"illegal page label format \"%s\"", 42},
  {"illegal non-printable format \"%s\"", 43},
  {"illegal style for wrapped line marker: \"%s\"", 44},
  {"illegal N-up argument: %d", 45},
  {"N-up argument must be power of 2: %d", 46},
  {"malformed underlay position: %s", 47},
  {"illegal underlay style: %s", 48},
  {"couldn't create toc file name: %s", 49},
  {"couldn't create toc file \"%s\": %s", 50},
  {"couldn't stat input file \"%s\": %s", 51},
  {"couldn't rewind toc file: %s", 52},
  {"Table of Contents", 53},
  {"no output generated\n", 54},
  {"output sent to %s\n", 55},
  {"printer", 56},
  {"output left in %s\n", 57},
  {"[ %d pages * %d copy ]", 58},
  {" sent to %s\n", 59},
  {" left in %s\n", 60},
  {"%d lines were %s\n", 61},
  {"truncated", 62},
  {"wrapped", 63},
  {"%d characters were missing\n", 64},
  {"missing character codes (decimal):\n", 65},
  {"%d non-printable characters\n", 66},
  {"non-printable character codes (decimal):\n", 67},
  {"couldn't open printer `%s': %s", 68},
  {"couldn't create output file \"%s\": %s", 69},
  {"\
syntax error in option string %s=\"%s\":\n\
missing end of quotation: %c", 70},
  {"\
warning: didn't process following options from environment variable %s:\n", 71},
  {"  option %d = \"%s\"\n", 72},
  {"file alignment must be larger than zero", 73},
  {"malformed font spec: %s", 74},
  {"couldn't find header definition file \"%s.hdr\"", 75},
  {"must print at least one line per each page: %s", 76},
  {"%s: illegal newline character specifier: '%s': expected 'n' or 'r'\n", 77},
  {"slice must be greater than zero", 78},
  {"Try `%s --help' for more information.\n", 79},
  {"\
Usage: %s [OPTION]... [FILE]...\n\
Mandatory arguments to long options are mandatory for short options too.\n\
  -#                         an alias for option -n, --copies\n\
  -1                         same as --columns=1\n\
  -2                         same as --columns=2\n\
      --columns=NUM          specify the number of columns per page\n\
  -a, --pages=PAGES          specify which pages are printed\n\
  -A, --file-align=ALIGN     align separate input files to ALIGN\n\
  -b, --header=HEADER        set page header\n\
  -B, --no-header            no page headers\n\
  -c, --truncate-lines       cut long lines (default is to wrap)\n\
  -C, --line-numbers[=START]\n\
                             precede each line with its line number\n\
  -d                         an alias for option --printer\n\
  -D, --setpagedevice=KEY[:VALUE]\n\
                             pass a page device definition to output\n\
  -e, --escapes[=CHAR]       enable special escape interpretation\n", 80},
  {"  -E, --pretty-print[=LANG]  pretty-print source code\n", 81},
  {"\
  -f, --font=NAME            use font NAME for body text\n\
  -F, --header-font=NAME     use font NAME for header texts\n\
  -g, --print-anyway         nothing (compatibility option)\n\
  -G                         same as --fancy-header\n\
      --fancy-header[=NAME]  select fancy page header\n\
  -h, --no-job-header        suppress the job header page\n\
  -H, --highlight-bars=NUM   specify how high highlight bars are\n\
  -i, --indent=NUM           set line indent to NUM characters\n\
  -I, --filter=CMD           read input files through input filter CMD\n\
  -j, --borders              print borders around columns\n\
  -J,                        an alias for option --title\n\
  -k, --page-prefeed         enable page prefeed\n\
  -K, --no-page-prefeed      disable page prefeed\n\
  -l, --lineprinter          simulate lineprinter, this is an alias for:\n\
                               --lines-per-page=66, --no-header, \
--portrait,\n\
                               --columns=1\n", 82},
  {"\
  -L, --lines-per-page=NUM   specify how many lines are printed on each \
page\n\
  -m, --mail                 send mail upon completion\n\
  -M, --media=NAME           use output media NAME\n\
  -n, --copies=NUM           print NUM copies of each page\n\
  -N, --newline=NL           select the newline character.  Possible\n\
                             values for NL are: n (`\\n') and r (`\\r').\n\
  -o                         an alias for option --output\n\
  -O, --missing-characters   list missing characters\n\
  -p, --output=FILE          leave output to file FILE.  If FILE is `-',\n\
                             leave output to stdout.\n\
  -P, --printer=NAME         print output to printer NAME\n\
  -q, --quiet, --silent      be really quiet\n\
  -r, --landscape            print in landscape mode\n\
  -R, --portrait             print in portrait mode\n", 83},
  {"\
  -s, --baselineskip=NUM     set baselineskip to NUM\n\
  -S, --statusdict=KEY[:VALUE]\n\
                             pass a statusdict definition to the output\n\
  -t, --title=TITLE          set banner page's job title to TITLE.  Option\n\
                             sets also the name of the input file stdin.\n\
  -T, --tabsize=NUM          set tabulator size to NUM\n\
  -u, --underlay[=TEXT]      print TEXT under every page\n\
  -U, --nup=NUM              print NUM logical pages on each output page\n\
  -v, --verbose              tell what we are doing\n\
  -V, --version              print version number\n\
  -W, --language=LANG        set output language to LANG\n\
  -X, --encoding=NAME        use input encoding NAME\n\
  -z, --no-formfeed          do not interpret form feed characters\n\
  -Z, --pass-through         pass through PostScript and PCL files\n\
                             without any modifications\n", 84},
  {"\
Long-only options:\n\
  --color[=COLOR]            set output color model to COLOR\n\
  --download-font=NAME       download font NAME\n\
  --filter-stdin=NAME        specify how stdin is shown to the input filter\n\
  --h-column-height=HEIGHT   set the horizontal column height to HEIGHT\n\
  --help                     print this help and exit\n\
  --help-pretty-print        describe all supported --pretty-print \
languages\n\
                             and file formats\n\
  --highlight-bar-gray=NUM   print highlight bars with gray NUM (0 - 1)\n\
  --list-media               list names of all known media\n\
  --list-options             list all options and their values\n\
  --margins=LEFT:RIGHT:TOP:BOTTOM\n\
                             adjust page marginals\n\
  --mark-wrapped-lines[STYLE]\n\
                             mark wrapped lines in the output with STYLE\n\
  --non-printable-format=FMT specify how non-printable chars are printed\n", 85},
  {"\
  --nup-xpad=NUM             set the page x-padding of N-up printing to NUM\n\
  --nup-ypad=NUM             set the page y-padding of N-up printing to NUM\n\
  --page-label-format=FMT    set page label format to FMT\n\
  --ps-level=LEVEL           set the PostScript language level that \
enscript\n\
                             should use\n\
  --printer-options=OPTIONS  pass extra options to the printer command\n\
  --rotate-even-pages        rotate even-numbered pages 180 degrees\n", 86},
  {"\
  --slice=NUM                print vertical slice NUM\n\
  --toc                      print table of contents\n\
  --ul-angle=ANGLE           set underlay text's angle to ANGLE\n\
  --ul-font=NAME             print underlays with font NAME\n\
  --ul-gray=NUM              print underlays with gray value NUM\n\
  --ul-position=POS          set underlay's starting position to POS\n\
  --ul-style=STYLE           print underlays with style STYLE\n\
  --word-wrap                wrap long lines from word boundaries\n", 87},
  {"\
\n\
Report bugs to mtr@iki.fi.\n", 88},
  {"couldn't find prolog \"%s\": %s\n", 89},
  {"couldn't find encoding file \"%s.enc\": %s\n", 90},
  {"couldn't find header definition file \"%s.hdr\": %s\n", 91},
  {"processing file \"%s\"...\n", 92},
  {"EPS file \"%s\" is too large for page\n", 93},
  {"unknown special escape: %s", 94},
  {"illegal option %c for ^@epsf escape", 95},
  {"malformed ^@epsf escape: no ']' after options", 96},
  {"\
too long file name for ^@epsf escape:\n\
%.*s", 97},
  {"unexpected EOF while scanning ^@epsf escape", 98},
  {"malformed ^@epsf escape: no '{' found", 99},
  {"malformed %s escape: no '{' found", 100},
  {"\
too long argument for %s escape:\n\
%.*s", 101},
  {"malformed font spec for ^@font escape: %s", 102},
  {"malformed color spec for ^@color escape: %s", 103},
  {"invalid value for ^@shade escape: %s", 104},
  {"invalid value for ^@bggray escape: %s", 105},
  {"epsf: couldn't open pipe to command \"%s\": %s\n", 106},
  {"couldn't open EPS file \"%s\": %s\n", 107},
  {"EPS file \"%s\" does not start with \"%%!\" magic\n", 108},
  {"\
EPS file \"%s\" contains malformed %%%%BoundingBox row:\n\
\"%.*s\"\n", 109},
  {"EPS file \"%s\" is not a valid EPS file\n", 110},
  {"passing through all input files for output language `%s'\n", 111},
  {"passing through %s file \"%s\"\n", 112},
  {"couldn't create divert file name: %s", 113},
  {"couldn't create divert file \"%s\": %s", 114},
  {"couldn't rewind divert file: %s", 115},
  {"illegal value \"%s\" for option %s", 116},
  {"invalid value \"%s\" for option %s", 117},
  {"illegal option: %s", 118},
  {"%s:%d: %%Format: no name", 119},
  {"%s:%d: %%Format: too long name, maxlen=%d", 120},
  {"%s:%d: %%Format: name \"%s\" is already defined", 121},
  {"%s:%d: %%HeaderHeight: no argument", 122},
  {"%s:%d: %%FooterHeight: no argument", 123},
  {"%s: warning: font size is negative\n", 124},
  {"%s: warning: font width is negative\n", 125},
  {"%s: warning: font height is negative\n", 126},
  {"reading AFM info for font \"%s\"\n", 127},
  {"couldn't open AFM file for font \"%s\", using default\n", 128},
  {"couldn't open AFM file for the default font: %s", 129},
  {"downloading font \"%s\"\n", 130},
  {"couldn't open font description file \"%s\": %s\n", 131},
  {"%s: too long format for %%D{} escape", 132},
  {"%s: unknown `%%' escape `%c' (%d)", 133},
  {"%s: no closing ')' for $() escape", 134},
  {"%s: too long variable name for $() escape", 135},
  {"%s: too long format for $D{} escape", 136},
  {"%s: unknown `$' escape `%c' (%d)", 137},
  {"malformed float dimension: \"%s\"", 138},
  {"couldn't open input filter \"%s\" for file \"%s\": %s", 139},
  {"couldn't open input file \"%s\": %s", 140},
  {"file=%s\n", 141},
  {"stdout", 142},
  {"%s: couldn't open output file \"%s\"", 143},
  {"couldn't create AFM library", 144},
  {"\
Usage: %s [OPTION]... FILE...\n\
Mandatory arguments to long options are mandatory for short options too.\n\
  -h, --help              print this help and exit\n\
  -p, --output-file=NAME  print output to file NAME (default file is\n\
                          font.map).  If FILE is `-', leavy output to\n\
                          stdout.\n\
  -V, --version           print version number\n", 145},
  {"states for GNU %s %s", 146},
  {"%s: malformed variable definition \"%s\"\n", 147},
  {"%s: couldn't create output file \"%s\": %s\n", 148},
  {"%s: unknown warning level `%s'\n", 149},
  {"%s: out of memory\n", 150},
  {"%s: couldn't open definition file `%s': %s\n", 151},
  {"%s: couldn't open input file `%s': %s\n", 152},
  {"\
Usage: %s [OPTION]... [FILE]...\n\
Mandatory arguments to long options are mandatory for short options too.\n", 153},
  {"\
  -D, --define=VAR=VAL       define variable VAR to have value VAR\n\
  -f, --file=NAME            read state definitions from file NAME\n\
  -h, --help                 print this help and exit\n\
  -o, --output=NAME          save output to file NAME\n\
  -s, --state=NAME           start from state NAME\n\
  -V, --version              print version number\n\
  -W, --warning=LEVEL        set the warning level to LEVEL\n", 154},
  {"%s:%d: %s: illegal argument type\n", 155},
  {"%s: panic: ", 156},
  {"%s:%d: %s: malformed version string `%s'\n", 157},
  {"\
%s: FATAL ERROR: States version %s or higher is required for this script\n", 158},
  {"%s:%d: %s: start offset is bigger than end offset\n", 159},
  {"%s:%d: %s: offset out of range\n", 160},
  {"%s:%d: %s: illegal argument\n", 161},
  {"%s:%d: %s: illegal regexp character syntax: %c\n", 162},
  {"%s: primitive `%s': too few arguments for format\n", 163},
  {"%s:%d: %s: argument %d doesn't match format\n", 164},
  {"%s:%d: %s: no extra options can be specified for %%s\n", 165},
  {"%s:%d: %s: illegal type specifier `%c'\n", 166},
  {"%s: undefined state `%s'\n", 167},
  {"%s: error: undefined variable `%s'\n", 168},
  {"%s:%d: couldn't compile regular expression \"%s\": %s\n", 169},
  {"%s: ouf of memory", 170},
  {"warning: redefining state `%s'", 171},
  {"%s:%d: warning: redefining subroutine `%s'\n", 172},
  {"%s:%d: error: undefined variable `%s'\n", 173},
  {"%s:%d: error: couldn't set variable `%s'\n", 174},
  {"%s:%d: error: expression between illegal types\n", 175},
  {"%s: too few arguments for subroutine\n", 176},
  {"%s: too many arguments for subroutine\n", 177},
  {"%s: undefined procedure `%s'\n", 178},
  {"%s:%d: error: illegal lvalue for assignment\n", 179},
  {"%s:%d: error: array reference index is not integer\n", 180},
  {"%s:%d: error: negative array reference index\n", 181},
  {"%s:%d: error: illegal rvalue for string assignment\n", 182},
  {"%s:%d: error: illegal type for array reference\n", 183},
  {"%s:%d: error: array reference index out of rance\n", 184},
};

int _msg_tbl_length = 184;
