INSTALL_AS_GROUP = tty      # (probably want to set both of these) 
INSTALL_PERMISSIONS = 6555  # If set, 'install' chmod's executable to this

after_install::
	$(LN) -f $(INSTALLED_PRODUCTS) $(DSTROOT)$(INSTALLDIR)/rdump
