#
# Makefile for pcmcia libDriver subdirectory. This is just used
# for installsrc.
#
# Exported and Private header files are enumerated separately for installation
# purposes.
#
# .c and .m files are enumerated in the common Makefile for build purposes.
#
PUBLIC_HFILES= 	
PRIVATE_HFILES=	

#
# Define where in DSTDIR this source goes.
#
MACHINE_DIR= pcmcia

tags:	always
	rm -f tags
	ctags *.[hm]

always:

# This does the rest.
-include ../../MakefileDir/Makefile.machine_common
