##
# Makefile for CVS
##

# Project info
Project               = cvs
Extra_Configure_Flags = --with-gssapi=/Local/Library/Frameworks/Kerberos.framework
Extra_LD_Flags        = -read_only_relocs warning -L/usr/local/lib
UserType              = Developer
ToolType              = Commands

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
