##
# Makefile for GNU m4
##

# Project info
Project               = m4
ProjectName           = gm4
UserType              = Developer
ToolType              = Commands
Extra_Configure_Flags = --program-prefix="g"
Extra_LD_Flags        = -read_only_relocs warning

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
