/*
 * This file was generated by the mkbuiltins program.
 */

#include <sys/cdefs.h>
#define BLTINCMD 0
#define BGCMD 1
#define BREAKCMD 2
#define CDCMD 3
#define DOTCMD 4
#define ECHOCMD 5
#define EVALCMD 6
#define EXECCMD 7
#define EXITCMD 8
#define EXPCMD 9
#define EXPORTCMD 10
#define FALSECMD 11
#define HISTCMD 12
#define FGCMD 13
#define GETOPTSCMD 14
#define HASHCMD 15
#define JOBIDCMD 16
#define JOBSCMD 17
#define LOCALCMD 18
#define PWDCMD 19
#define READCMD 20
#define RETURNCMD 21
#define SETCMD 22
#define SETVARCMD 23
#define SHIFTCMD 24
#define TRAPCMD 25
#define TRUECMD 26
#define UMASKCMD 27
#define UNALIASCMD 28
#define UNSETCMD 29
#define WAITCMD 30
#define ALIASCMD 31
#define ULIMITCMD 32

struct builtincmd {
      char *name;
      int code;
};

extern int (*const builtinfunc[])();
extern const struct builtincmd builtincmd[];
