#!/usr/bin/perl

# $RCSfile: ged,v $$Revision: 1.1.1.1 $$Date: 1999/04/23 01:27:52 $

# Does inplace edits on a set of files on a set of machines.
#
# Typical invokation:
#
#	ged vax+sun /etc/passwd
#	s/Freddy/Freddie/;
#	^D
#

$class = shift;
$files = join(' ',@ARGV);

die "Usage: ged class files <perlcmds\n" unless $files;

exec "gsh", $class, "-d", "perl -pi.bak - $files";

die "Couldn't execute gsh for some reason, stopped";
