/*
 * Copyright (c) 1999 Apple Computer, Inc. All rights reserved.
 *
 * @APPLE_LICENSE_HEADER_START@
 * 
 * Portions Copyright (c) 1999 Apple Computer, Inc.  All Rights
 * Reserved.  This file contains Original Code and/or Modifications of
 * Original Code as defined in and that are subject to the Apple Public
 * Source License Version 1.1 (the "License").  You may not use this file
 * except in compliance with the License.  Please obtain a copy of the
 * License at http://www.apple.com/publicsource and read it before using
 * this file.
 * 
 * The Original Code and all software distributed under the License are
 * distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 * EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE OR NON- INFRINGEMENT.  Please see the
 * License for the specific language governing rights and limitations
 * under the License.
 * 
 * @APPLE_LICENSE_HEADER_END@
 */
// diskstruct.h -- generated by gendisk.c
// DON'T EDIT THIS -- change gendisk.c


//
// Structure Offsets
//

// disk_label_t offsets

#define	DISK_LABEL_DL_VERSION         0x00000000
#define	DISK_LABEL_DL_LABEL_BLKNO     0x00000004
#define	DISK_LABEL_DL_SIZE            0x00000008
#define	DISK_LABEL_DL_LABEL           0x0000000c
#define	DISK_LABEL_DL_FLAGS           0x00000024
#define	DISK_LABEL_DL_TAG             0x00000028
#define	DISK_LABEL_DL_DT              0x0000002c
#define	DISK_LABEL_DL_UN              0x0000022e
#define	DISK_LABEL_DL_CHECKSUM        0x00001c46
#define	SIZEOF_DISK_LABEL_T           7240
#define	SIZEOF_DL_UN_T                6680

// disktab_t offsets

#define	DISKTAB_D_NAME                0x00000000
#define	DISKTAB_D_TYPE                0x00000018
#define	DISKTAB_D_SECSIZE             0x00000030
#define	DISKTAB_D_NTRACKS             0x00000034
#define	DISKTAB_D_NSECTORS            0x00000038
#define	DISKTAB_D_NCYLINDERS          0x0000003c
#define	DISKTAB_D_RPM                 0x00000040
#define	DISKTAB_D_FRONT               0x00000044
#define	DISKTAB_D_BACK                0x00000046
#define	DISKTAB_D_NGROUPS             0x00000048
#define	DISKTAB_D_AG_SIZE             0x0000004a
#define	DISKTAB_D_AG_ALTS             0x0000004c
#define	DISKTAB_D_AG_OFF              0x0000004e
#define	DISKTAB_D_BOOT0_BLKNO         0x00000050
#define	DISKTAB_D_BOOTFILE            0x00000058
#define	DISKTAB_D_HOSTNAME            0x00000070
#define	DISKTAB_D_ROOTPARTITION       0x00000090
#define	DISKTAB_D_RWPARTITION         0x00000091
#define	DISKTAB_D_PARTITIONS          0x00000092
#define	SIZEOF_DISKTAB_T              514

// partition_t offsets

#define	PARTITION_P_BASE              0x00000000
#define	PARTITION_P_SIZE              0x00000004
#define	PARTITION_P_BSIZE             0x00000008
#define	PARTITION_P_FSIZE             0x0000000a
#define	PARTITION_P_OPT               0x0000000c
#define	PARTITION_P_CPG               0x0000000e
#define	PARTITION_P_DENSITY           0x00000010
#define	PARTITION_P_MINFREE           0x00000012
#define	PARTITION_P_NEWFS             0x00000013
#define	PARTITION_P_MOUNTPT           0x00000014
#define	PARTITION_P_AUTOMNT           0x00000024
#define	PARTITION_P_TYPE              0x00000025
#define	SIZEOF_PARTITION_T            46
