#!/bin/sh -
#
#	@(#)daily	8.2 (Berkeley) 1/25/94
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
host=`hostname`
echo "Subject: $host daily run output"
bak=/var/backups

echo ""
echo "Removing scratch and junk files:"

if [ -d /var/rwho ] ; then
	cd /var/rwho && {
	find . ! -name . -mtime +7 -exec rm -f -- {} \; ; }
fi

# This is a security hole: never use 'find' on a public directory
# with -exec rm -f as root.  This can be exploited to delete any file
# on the system.

find / \( ! -fstype local -o -fstype rdonly \) -a -prune -o \
       \( -name '[#,]*' -o -name '.#*' -o -name a.out -o -name '*.core' \
	  -o -name '*.CKP' -o -name '.emacs_[0-9]*' \) \
	       -a -atime +3 -exec rm -f -- {} \;

if [ "${host}" != "localhost" ]; then
	find / -name .nfs\* -mtime +7 -exec rm -f -- {} \; -o -fstype nfs -prune
fi

# The same security hole.  Purge the temp directories from unused stuff.
#
# Use at your own risk, but for a long-living system, this might come
# more useful than the boot-time cleaning of /tmp.  If /var/tmp and
# /tmp are symlinked together, only one of the below will actually
# run.

if [ -d /tmp ]; then
	cd /tmp && {
	find . -type f -atime +3 -ctime +3 -exec rm -f -- {} \;
	find -d . ! -name . -type d -mtime +1 -exec rmdir -- {} \; \
	    >/dev/null 2>&1; }
fi

if [ -d /var/tmp ]; then
	cd /var/tmp && {
	find . ! -name . -atime +7 -ctime +3 -exec rm -f -- {} \;
	find -d . ! -name . -type d -mtime +1 -exec rmdir -- {} \; \
	    >/dev/null 2>&1; }
fi

# remove system messages older than 21 days
msgs -c

if [ -f /etc/news.expire ]; then
	/etc/news.expire
fi

if [ -f /var/account/acct ] ; then
	if [ -x /usr/bin/gzip ]; then gzext=".gz"; else gzext=""; fi
	echo ""
	echo "Gathering accounting statistics:"
	cd /var/account
	if [ -f "acct.2${gzext}" ] ; then mv -f "acct.2${gzext}" "acct.3${gzext}" ; fi
	if [ -f "acct.1${gzext}" ] ; then mv -f "acct.1${gzext}" "acct.2${gzext}" ; fi
	if [ -f "acct.0${gzext}" ] ; then mv -f "acct.0${gzext}" "acct.1${gzext}" ; fi
	cp -pf acct acct.0
	if [ -x /usr/bin/gzip ]; then gzip -9 acct.0; fi
	sa -s > /dev/null
fi

echo ""
if [ -f /etc/Distfile ]; then
	if cmp -s $bak/Distfile.bak /etc/Distfile; then :; else
		mv $bak/Distfile.bak $bak/Distfile.bak2
		cp /etc/Distfile $bak/Distfile.bak
	fi
fi
if [ -d /etc/netinfo ]; then
	cd /etc
	pax -pe -rw netinfo $bak
fi

if [ -d /var/spool/uucp -a -f /etc/uuclean.daily ]; then
	echo ""
	echo "Cleaning up UUCP:"
	echo /etc/uuclean.daily | su daemon
fi

echo ""
echo ""
echo "Checking subsystem status:"
echo ""
echo "disks:"
df -k -t local
echo ""
dump W
echo ""


#echo ""
#echo "mail:"
#mailq

if [ -d /var/spool/uucp ]; then
	echo ""
	echo "uucp:"
	uustat -a
fi

echo ""
echo "network:"
netstat -i
echo ""
if [ -d /var/rwho ] ; then
	ruptime
fi

echo ""
if [ -f /etc/Distfile ]; then
	echo "Running rdist:"
	rdist -f /etc/Distfile
fi

echo ""
echo -n "Rotating log files:"
cd /var/log
for i in system.log; do
	echo -n " ${i}"
	if [ -x /usr/bin/gzip ]; then gzext=".gz"; else gzext=""; fi
	if [ -f "${i}.6${gzext}" ]; then mv -f "${i}.6${gzext}" "${i}.7${gzext}"; fi
	if [ -f "${i}.5${gzext}" ]; then mv -f "${i}.5${gzext}" "${i}.6${gzext}"; fi
	if [ -f "${i}.4${gzext}" ]; then mv -f "${i}.4${gzext}" "${i}.5${gzext}"; fi
	if [ -f "${i}.3${gzext}" ]; then mv -f "${i}.3${gzext}" "${i}.4${gzext}"; fi
	if [ -f "${i}.2${gzext}" ]; then mv -f "${i}.2${gzext}" "${i}.3${gzext}"; fi
	if [ -f "${i}.1${gzext}" ]; then mv -f "${i}.1${gzext}" "${i}.2${gzext}"; fi
	if [ -f "${i}.0${gzext}" ]; then mv -f "${i}.0${gzext}" "${i}.1${gzext}"; fi
	if [ -f "${i}" ]; then mv -f "${i}" "${i}.0" && if [ -x /usr/bin/gzip ]; then gzip -9 "${i}.0"; fi; fi
	touch "${i}" && chmod 640 "${i}"
done
if [ -f /var/run/syslog.pid ]; then kill -HUP $(cat /var/run/syslog.pid | head -1); fi
echo ""

echo ""
echo -n "Cleaning web server log files:"
if [ -d /Local/Library/WebServer/Logs ]; then
	cd /Local/Library/WebServer/Logs && {
	find . -type f -name '*_log.*' -mtime +7 -exec rm -f -- {} \; >/dev/null 2>&1; }
fi

if [ -f /etc/daily.local ]; then
    echo "Running daily.local:"
    sh /etc/daily.local
fi

if [ -f /etc/security ]; then
    sh /etc/security 2>&1 | sendmail root
fi
