##
# Makefile for Tcl
##

# Project info
Project        = tcl
UserType       = Developer
ToolType       = Commands
Configure      = $(Sources)/unix/configure
Extra_CC_Flags = -traditional-cpp

# It's a GNU Source project
include $(MAKEFILEPATH)/CoreOS/ReleaseControl/GNUSource.make

Install_Target = install
Install_Flags  = INSTALL_ROOT="$(DSTROOT)"
