##
# Makefile for Bison
##

# Project info
Project  = bison
UserType = Developer
ToolType = Commands

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
