##
# Makefile for zsh
##

# Project info
Project               = zsh
Extra_Configure_Flags = --bindir="/bin"
Extra_Install_Flags   = bindir="$(DSTROOT)/bin"
UserType              = Administration
ToolType              = Commands

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
