##
# Makefile for grep
##

# Project info
Project  = grep
UserType = Administration
ToolType = Commands

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
