##
# Makefile for rsync
##

# Project info
Project  = rsync
UserType = Administration
ToolType = Commands

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
