##
# Makefile for diffutils
##

# Project info
Project        = diffutils
UserType       = Administration
ToolType       = Commands
Extra_LD_Flags = -read_only_relocs warning

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
