##
# Makefile for Patch
##

# Project info
Project        = patch
UserType       = Developer
ToolType       = Commands

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
