##
# Makefile for less
##

# Project info
Project  = less
UserType = Administration
ToolType = Commands

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
