##
# Makefile for gawk
##

# Project info
Project  = gawk
UserType = Administration
ToolType = Commands

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
