/* Automatically generated by po2tbl.sed from tar.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Total bytes written: ", 2},
  {"Cannot close file #%d", 3},
  {"Cannot close descriptor %d", 4},
  {"Cannot properly duplicate %s", 5},
  {"Cannot use compressed or remote archives", 6},
  {"Cannot open pipe", 7},
  {"Cannot fork", 8},
  {"tar (child)", 9},
  {"(child) Pipe to stdin", 10},
  {"Cannot open archive %s", 11},
  {"Archive to stdout", 12},
  {"Cannot exec %s", 13},
  {"Child cannot fork", 14},
  {"((child)) Pipe to stdout", 15},
  {"tar (grandchild)", 16},
  {"(grandchild) Pipe to stdin", 17},
  {"Cannot read from compression program", 18},
  {"(child) Pipe to stdout", 19},
  {"Archive to stdin", 20},
  {"((child)) Pipe to stdin", 21},
  {"(grandchild) Pipe to stdout", 22},
  {"Cannot write to compression program", 23},
  {"Write to compression program short %d bytes", 24},
  {"Invalid value for record_size", 25},
  {"No archive name given", 26},
  {"Could not allocate memory for blocking factor %d", 27},
  {"Cannot verify multi-volume archives", 28},
  {"Cannot use multi-volume compressed archives", 29},
  {"Cannot verify compressed archives", 30},
  {"Cannot update compressed archives", 31},
  {"Cannot verify stdin/stdout archive", 32},
  {"Cannot open %s", 33},
  {"Archive not labelled to match `%s'", 34},
  {"Volume `%s' does not match `%s'", 35},
  {"Write checkpoint %d", 36},
  {"Cannot write to %s", 37},
  {"Only wrote %u of %u bytes to %s", 38},
  {"Read error on %s", 39},
  {"At beginning of tape, quitting now", 40},
  {"Too many errors, quitting", 41},
  {"Read checkpoint %d", 42},
  {"Reading %s\n", 43},
  {"WARNING: No volume header", 44},
  {"%s is not continued on this volume", 45},
  {"%s is the wrong size (%ld != %ld + %ld)", 46},
  {"This volume is out of sequence", 47},
  {"Record size = %d blocks", 48},
  {"Archive %s EOF not on block boundary", 49},
  {"Only read %d bytes from archive %s", 50},
  {"WARNING: Cannot close %s (%d, %d)", 51},
  {"Could not backspace archive file; it may be unreadable without -i", 52},
  {"Child died with signal %d%s", 53},
  {" (core dumped)", 54},
  {"Child returned status %d", 55},
  {"Prepare volume #%d for %s and hit return: ", 56},
  {"EOF where user reply was expected", 57},
  {"WARNING: Archive is incomplete", 58},
  {"\
 n [name]   Give a new file name for the next (and subsequent) volume(s)\n\
 q          Abort tar\n\
 !          Spawn a subshell\n\
 ?          Print this list\n", 59},
  {"No new volume; exiting.\n", 60},
  {"Cannot fork!", 61},
  {"Cannot exec a shell %s", 62},
  {"Removing drive spec from names in the archive", 63},
  {"Removing leading `/' from absolute path names in the archive", 64},
  {"Wrote %ld of %ld bytes to file %s", 65},
  {"Read error at byte %ld, reading %d bytes, in file %s", 66},
  {"File %s shrunk by %d bytes, padding with zeros", 67},
  {"Amount actually written is (I hope) %d.\n", 68},
  {"Cannot add file %s", 69},
  {"%s: is unchanged; not dumped", 70},
  {"%s is the archive; not dumped", 71},
  {"Removing leading `/' from absolute links", 72},
  {"Cannot remove %s", 73},
  {"Cannot add directory %s", 74},
  {"%s: On a different filesystem; not dumped", 75},
  {"Cannot open directory %s", 76},
  {"File name %s%s too long", 77},
  {"%s: Unknown file type; file ignored", 78},
  {"Could not allocate memory for diff buffer of %d bytes", 79},
  {"Cannot read %s", 80},
  {"Could only read %d of %ld bytes", 81},
  {"Data differs", 82},
  {"Unexpected EOF on archive file", 83},
  {"File does not exist", 84},
  {"Cannot stat file %s", 85},
  {"Verify ", 86},
  {"Unknown file type '%c' for %s, diffed as normal file", 87},
  {"Not a regular file", 88},
  {"Mode differs", 89},
  {"Uid differs", 90},
  {"Gid differs", 91},
  {"Mod time differs", 92},
  {"Size differs", 93},
  {"Error while closing %s", 94},
  {"Does not exist", 95},
  {"Not linked to %s", 96},
  {"No such file or directory", 97},
  {"Cannot read link %s", 98},
  {"Symlink differs", 99},
  {"Device numbers changed", 100},
  {"Mode or device-type changed", 101},
  {"No longer a directory", 102},
  {"Cannot open file %s", 103},
  {"Cannot seek to %ld in file %s", 104},
  {"Could not rewind archive file for verify", 105},
  {"VERIFY FAILURE: %d invalid header(s) detected", 106},
  {"Could not re-position archive file", 107},
  {"This does not look like a tar archive", 108},
  {"Skipping to next header", 109},
  {"Deleting non-header from archive", 110},
  {"%s: Cannot change mode to %0.4o", 111},
  {"%s: Could not change access and modification times", 112},
  {"%s: Cannot lchown to uid %d gid %d", 113},
  {"%s: Cannot chown to uid %d gid %d", 114},
  {"%s: Cannot change owner to uid %d, gid %d", 115},
  {"%s: Could not write to file", 116},
  {"%s: Could only write %d of %d bytes", 117},
  {"%s: Was unable to backup this file", 118},
  {"Extracting contiguous files as regular files", 119},
  {"%s: Could not create file", 120},
  {"%d at %d\n", 121},
  {"%s: Error while closing", 122},
  {"%s: Could not create symlink to `%s'", 123},
  {"Attempting extraction of symbolic links as hard links", 124},
  {"%s: Could not link to `%s'", 125},
  {"%s: Could not make node", 126},
  {"%s: Could not make fifo", 127},
  {"%s: Could not create directory", 128},
  {"Added write and execute permission to directory %s", 129},
  {"Cannot extract `%s' -- file is continued from another volume", 130},
  {"Visible long name error", 131},
  {"Unknown file type '%c' for %s, extracted as normal file", 132},
  {"Cannot stat %s", 133},
  {"Directory %s has been renamed", 134},
  {"Directory %s is new", 135},
  {"Could not get current directory", 136},
  {"Could not get current directory: %s", 137},
  {"File name %s/%s too long", 138},
  {"Cannot chdir to %s", 139},
  {"Unexpected EOF in archive", 140},
  {"%s: Deleting %s\n", 141},
  {"Error while deleting %s", 142},
  {"Omitting %s", 143},
  {"block %10ld: ** Block of NULs **\n", 144},
  {"block %10ld: ** End of File **\n", 145},
  {"Hmm, this doesn't look like a tar archive", 146},
  {"Skipping to next file header", 147},
  {"EOF in archive file", 148},
  {"Only wrote %ld of %ld bytes to file %s", 149},
  {"block %10ld: ", 150},
  {"Visible longname error", 151},
  {" link to %s\n", 152},
  {" unknown file type `%c'\n", 153},
  {"--Volume Header--\n", 154},
  {"--Continued at byte %ld--\n", 155},
  {"--Mangled file names--\n", 156},
  {"Creating directory:", 157},
  {"Unexpected EOF in mangled names", 158},
  {"Cannot rename %s to %s", 159},
  {"Renamed %s to %s", 160},
  {"Cannot symlink %s to %s", 161},
  {"Symlinked %s to %s", 162},
  {"Unknown demangling command %s", 163},
  {"Cannot change to directory %s", 164},
  {"Missing file name after -C", 165},
  {"%s: Not found in archive", 166},
  {"Unknown system error", 167},
  {"rmtd: Cannot allocate buffer space\n", 168},
  {"Cannot allocate buffer space", 169},
  {"rmtd: Premature eof\n", 170},
  {"Premature end of file", 171},
  {"rmtd: Garbage command %c\n", 172},
  {"Garbage command", 173},
  {"exec/tcp: Service not available", 174},
  {"stdin", 175},
  {"stdout", 176},
  {"Cannot execute remote shell", 177},
  {"Options `-%s' and `-%s' both want standard input", 178},
  {"Cannot read confirmation from user", 179},
  {"Try `%s --help' for more information.\n", 180},
  {"\
GNU `tar' saves many files together into a single tape or disk archive, and\n\
can restore individual files from the archive.\n", 181},
  {"\
\n\
Usage: %s [OPTION]... [FILE]...\n", 182},
  {"\
\n\
If a long option shows an argument as mandatory, then it is mandatory\n\
for the equivalent short option also.  Similarly for optional arguments.\n", 183},
  {"\
\n\
Main operation mode:\n\
  -t, --list              list the contents of an archive\n\
  -x, --extract, --get    extract files from an archive\n\
  -c, --create            create a new archive\n\
  -d, --diff, --compare   find differences between archive and file system\n\
  -r, --append            append files to the end of an archive\n\
  -u, --update            only append files newer than copy in archive\n\
  -A, --catenate          append tar files to an archive\n\
      --concatenate       same as -A\n\
      --delete            delete from the archive (not on mag tapes!)\n", 184},
  {"\
\n\
Operation modifiers:\n\
  -W, --verify               attempt to verify the archive after writing it\n\
      --remove-files         remove files after adding them to the archive\n\
  -k, --keep-old-files       don't overwrite existing files when extracting\n\
  -U, --unlink-first         remove each file prior to extracting over it\n\
      --recursive-unlink     empty hierarchies prior to extracting \
directory\n\
  -S, --sparse               handle sparse files efficiently\n\
  -O, --to-stdout            extract files to standard output\n\
  -G, --incremental          handle old GNU-format incremental backup\n\
  -g, --listed-incremental   handle new GNU-format incremental backup\n\
      --ignore-failed-read   do not exit with nonzero on unreadable files\n", 185},
  {"\
\n\
Handling of file attributes:\n\
      --owner=NAME             force NAME as owner for added files\n\
      --group=NAME             force NAME as group for added files\n\
      --mode=CHANGES           force (symbolic) mode CHANGES for added \
files\n\
      --atime-preserve         don't change access times on dumped files\n\
  -m, --modification-time      don't extract file modified time\n\
      --same-owner             try extracting files with the same ownership\n\
      --numeric-owner          always use numbers for user/group names\n\
  -p, --same-permissions       extract all protection information\n\
      --preserve-permissions   same as -p\n\
  -s, --same-order             sort names to extract to match archive\n\
      --preserve-order         same as -s\n\
      --preserve               same as both -p and -s\n", 186},
  {"\
\n\
Device selection and switching:\n\
  -f, --file=ARCHIVE             use archive file or device ARCHIVE\n\
      --force-local              archive file is local even if has a colon\n\
      --rsh-command=COMMAND      use remote COMMAND instead of rsh\n\
  -[0-7][lmh]                    specify drive and density\n\
  -M, --multi-volume             create/list/extract multi-volume archive\n\
  -L, --tape-length=NUM          change tape after writing NUM x 1024 bytes\n\
  -F, --info-script=FILE         run script at end of each tape (implies \
-M)\n\
      --new-volume-script=FILE   same as -F FILE\n\
      --volno-file=FILE          use/update the volume number in FILE\n", 187},
  {"\
\n\
Device blocking:\n\
  -b, --blocking-factor=BLOCKS   BLOCKS x 512 bytes per record\n\
      --record-size=SIZE         SIZE bytes per record, multiple of 512\n\
  -i, --ignore-zeros             ignore zeroed blocks in archive (means \
EOF)\n\
  -B, --read-full-records        reblock as we read (for 4.2BSD pipes)\n", 188},
  {"\
\n\
Archive format selection:\n\
  -V, --label=NAME                   create archive with volume name NAME\n\
              PATTERN                at list/extract time, a globbing \
PATTERN\n\
  -o, --old-archive, --portability   write a V7 format archive\n\
      --posix                        write a POSIX conformant archive\n\
  -z, --gzip, --ungzip               filter the archive through gzip\n\
  -Z, --compress, --uncompress       filter the archive through compress\n\
      --use-compress-program=PROG    filter through PROG (must accept -d)\n", 189},
  {"\
\n\
Local file selection:\n\
  -C, --directory=DIR          change to directory DIR\n\
  -T, --files-from=NAME        get names to extract or create from file \
NAME\n\
      --null                   -T reads null-terminated names, disable -C\n\
      --exclude=PATTERN        exclude files, given as a globbing PATTERN\n\
  -X, --exclude-from=FILE      exclude globbing patterns listed in FILE\n\
  -P, --absolute-names         don't strip leading `/'s from file names\n\
  -h, --dereference            dump instead the files symlinks point to\n\
      --no-recursion           avoid descending automatically in \
directories\n\
  -l, --one-file-system        stay in local file system when creating \
archive\n\
  -K, --starting-file=NAME     begin at file NAME in the archive\n", 190},
  {"\
  -N, --newer=DATE             only store files newer than DATE\n\
      --newer-mtime            compare date and time when data changed only\n\
      --after-date=DATE        same as -N\n", 191},
  {"\
      --backup[=CONTROL]       backup before removal, choose version \
control\n\
      --suffix=SUFFIX          backup before removel, override usual suffix\n", 192},
  {"\
\n\
Informative output:\n\
      --help            print this help, then exit\n\
      --version         print tar program version number, then exit\n\
  -v, --verbose         verbosely list files processed\n\
      --checkpoint      print directory names while reading the archive\n\
      --totals          print total bytes written while creating archive\n\
  -R, --block-number    show block number within archive with each message\n\
  -w, --interactive     ask for confirmation for every action\n\
      --confirmation    same as -w\n", 193},
  {"\
\n\
The backup suffix is `~', unless set with --suffix or SIMPLE_BACKUP_SUFFIX.\n\
The version control may be set with --backup or VERSION_CONTROL, values \
are:\n\
\n\
  t, numbered     make numbered backups\n\
  nil, existing   numbered if numbered backups exist, simple otherwise\n\
  never, simple   always make simple backups\n", 194},
  {"\
\n\
GNU tar cannot read nor produce `--posix' archives.  If POSIXLY_CORRECT\n\
is set in the environment, GNU extensions are disallowed with `--posix'.\n\
Support for POSIX is only partially implemented, don't count on it yet.\n\
ARCHIVE may be FILE, HOST:FILE or USER@HOST:FILE; and FILE may be a file\n\
or a device.  *This* `tar' defaults to `-f%s -b%d'.\n", 195},
  {"\
\n\
Report bugs to <tar-bugs@gnu.ai.mit.edu>.\n", 196},
  {"You may not specify more than one `-Acdtrux' option", 197},
  {"Conflicting compression options", 198},
  {"Old option `%c' requires an argument.", 199},
  {"Obsolete option, now implied by --blocking-factor", 200},
  {"Obsolete option name replaced by --blocking-factor", 201},
  {"Obsolete option name replaced by --read-full-records", 202},
  {"Obsolete option name replaced by --touch", 203},
  {"More than one threshold date", 204},
  {"Invalid date format `%s'", 205},
  {"Conflicting archive format options", 206},
  {"Obsolete option name replaced by --absolute-names", 207},
  {"Obsolete option name replaced by --block-number", 208},
  {"Obsolete option name replaced by --backup", 209},
  {"Invalid group given on option", 210},
  {"Invalid mode given on option", 211},
  {"Memory exhausted", 212},
  {"Invalid owner given on option", 213},
  {"Record size must be a multiple of %d.", 214},
  {"Options `-[0-7][lmh]' not supported by *this* tar", 215},
  {"\
\n\
Copyright (C) 1988, 92, 93, 94, 95, 96, 97 Free Software Foundation, Inc.\n", 216},
  {"\
This is free software; see the source for copying conditions.  There is NO\n\
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n", 217},
  {"\
\n\
Written by John Gilmore and Jay Fenlason.\n", 218},
  {"GNU features wanted on incompatible archive format", 219},
  {"Multiple archive files requires `-M' option", 220},
  {"Cowardly refusing to create an empty archive", 221},
  {"Options `-Aru' are incompatible with `-f -'", 222},
  {"You must specify one of the `-Acdtrux' options", 223},
  {"Error exit delayed from previous errors", 224},
  {"Read error at byte %ld reading %d bytes in file %s", 225},
  {"%s: File shrunk by %d bytes, (yark!)", 226},
  {"Generate data files for GNU tar test suite.\n", 227},
  {"\
\n\
Usage: %s [OPTION]...\n", 228},
  {"\
If a long option shows an argument as mandatory, then it is mandatory\n\
for the equivalent short option also.\n\
\n\
  -l, --file-length=LENGTH   LENGTH of generated file\n\
  -p, --pattern=PATTERN      PATTERN is `default' or `zeros'\n\
      --help                 display this help and exit\n\
      --version              output version information and exit\n", 229},
  {"Ambiguous pattern `%s'", 230},
  {"Unknown pattern `%s'", 231},
  {"\
\n\
Copyright (C) 1995, 1996, 1997 Free Software Foundation, Inc.\n", 232},
  {"\
\n\
Written by François Pinard <pinard@iro.umontreal.ca>.\n", 233},
};
int _msg_tbl_length = 233;
