# Note: This includes the telnet command high above us

VPATH_PREAMBLE = ../api:../ascii:../ctlr:/../general:../sys_curses:../../telnet:

OTHER_OFILES = apilib.o api_bsd.o api_exch.o asc_ebc.o astosc.o dctype.o \
	disp_asc.o ebc_disp.o map3270.o termin.o \
	api.o function.o inbound.o oia.o options.o outbound.o \
	genbsubs.o globals.o system.o termout.o \
	commands.o main.o network.o ring.o sys_bsd.o telnet.o terminal.o \
	tn3270.o utilities.o

-include ../../Makefile.include
