##
# Makefile for bc
##

# Project info
Project  = bc
UserType = Administration
ToolType = Commands

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
