/*
 * Copyright (c) 1999 Apple Computer, Inc. All rights reserved.
 *
 * @APPLE_LICENSE_HEADER_START@
 * 
 * Portions Copyright (c) 1999 Apple Computer, Inc.  All Rights
 * Reserved.  This file contains Original Code and/or Modifications of
 * Original Code as defined in and that are subject to the Apple Public
 * Source License Version 1.1 (the "License").  You may not use this file
 * except in compliance with the License.  Please obtain a copy of the
 * License at http://www.apple.com/publicsource and read it before using
 * this file.
 * 
 * The Original Code and all software distributed under the License are
 * distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 * EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE OR NON- INFRINGEMENT.  Please see the
 * License for the specific language governing rights and limitations
 * under the License.
 * 
 * @APPLE_LICENSE_HEADER_END@
 */

/*
 * Copyright (c) 1992 NeXT Computer, Inc.
 *
 * Intel386 Family:	Trap identifiers.
 *
 * HISTORY
 *
 * 13 April 1992 ? at NeXT
 *	Created.
 */

/*
 * Exceptions which are generated by the
 * hardware.  There are 3 different classes:
 *
 * FAULT -	Generated before an instruction.  On
 *		return, the instruction is restarted.
 *
 * TRAP  -	Generated after an instruction.  On
 *		return, the next instruction is started.
 *
 * ABORT -	Does not permit restart or continuation.
 */
#define T_ZERO_DIVIDE		0	/*	FAULT	*/
#define T_DEBUG			1	/*	TRAP	*/
#define T_BREAKPOINT		3	/*	TRAP	*/
#define T_OVERFLOW		4	/*	TRAP	*/
#define T_BOUNDS_CHECK		5	/*	FAULT	*/
#define T_INVALID_OPCODE	6	/*	FAULT	*/
#define T_NOEXTENSION		7	/*	FAULT	*/
#define T_DOUBLE_FAULT		8	/*	FAULT	*/
#define T_EXTENSION_OVERRUN	9	/*	ABORT	*/
#define T_INVALID_TSS		10	/*	FAULT	*/
#define T_SEGMENT_NOTPRESENT	11	/*	FAULT	*/
#define T_STACK_EXCEPTION	12	/*	FAULT	*/
#define T_GENERAL_PROTECTION	13	/*	FAULT	*/
#define T_PAGE_FAULT		14	/*	FAULT	*/
#define T_EXTENSION_FAULT	16	/*	FAULT	*/
#define T_ALIGNMENT_CHECK	17	/*	FAULT	*/
