##
# Makefile for autoconf
##

# Project info
Project  = autoconf
UserType = Developer
ToolType = Commands

# It's a GNU Source project
include /System/Developer/Makefiles/CoreOS/ReleaseControl/GNUSource.make
