@echo off
echo Configuring glob for GO32
rem This batch file assumes a unix-type "sed" program

echo echo config.status unused by NT > config.status

echo # Makefile generated by "configure.bat"> Makefile

if exist config.sed del config.sed

echo "s/@srcdir@/./					">> config.sed
echo "s/@CC@/gcc/					">> config.sed
echo "s/@CFLAGS@/-g -O/					">> config.sed
echo "s/@CPPFLAGS@/-DHAVE_CONFIG_H -DNO_ARCHIVES -I../	">> config.sed
echo "s/@AR@/libtool/					">> config.sed
echo "s/ARFLAGS = .*/ARFLAGS = -static -o/		">> config.sed
echo "s/@RANLIB@/touch/					">> config.sed
echo "s/@LDFLAGS@/-g/					">> config.sed
echo "s/@DEFS@//					">> config.sed
echo "s/@ALLOCA@//					">> config.sed
echo "s/@LIBS@//					">> config.sed
echo "s/@LIBOBJS@//					">> config.sed
echo "s/^Makefile *:/_Makefile:/			">> config.sed
echo "s/^config.h *:/_config.h:/			">> config.sed

sed -e "s/^\"//" -e "s/\"$//" -e "s/[ 	]*$//" config.sed > config2.sed
sed -f config2.sed Makefile.in >> Makefile
del config.sed
del config2.sed
