@echo off
echo Configuring MAKE for go32
rem This batch file assumes a unix-type "sed" program

echo echo config.status unused by NT > config.status

if exist config.h del config.h
copy configh.dos config.h

echo # Makefile generated by "configure.bat"> Makefile

if exist config.sed del config.sed

echo ": try_sl						">> config.sed
echo "/\\$/ {						">> config.sed
echo "  N						">> config.sed
echo "  s/[ 	]*\\\n[ 	]*/ /			">> config.sed
echo "  b try_sl					">> config.sed
echo "}							">> config.sed

echo "s/@srcdir@/./					">> config.sed
echo "s/@CC@/gcc/					">> config.sed
echo "s/@CFLAGS@/-g -O/					">> config.sed
echo "s/@CPPFLAGS@/-DHAVE_CONFIG_H -DNO_ARCHIVES/ 	">> config.sed
echo "s/@LDFLAGS@/-g/					">> config.sed
echo "s/@RANLIB@/touch/					">> config.sed
echo "s/@DEFS@//					">> config.sed
echo "s/@REMOTE@/stub/					">> config.sed
echo "s/@ALLOCA@//					">> config.sed
echo "s/@LIBS@//					">> config.sed
echo "s/@LIBOBJS@//					">> config.sed
echo "s/@SET_MAKE@//					">> config.sed
echo "s/@prefix@/\/usr\/local/				">> config.sed
echo "s/@exec_prefix@/$(prefix)/			">> config.sed
echo "s/@NEED_SETGID@/false/				">> config.sed
echo "s/@KMEM_GROUP@//					">> config.sed
echo "s/@INSTALL_PROGRAM@/$(INSTALL)/			">> config.sed
echo "s/@INSTALL_DATA@/$(INSTALL) -m 644/		">> config.sed
echo "s/@INSTALL@/.\/install-sh -c/			">> config.sed
echo "s/^Makefile *:/Makefile:/				">> config.sed
echo "s/^config.h *:/config.h:/				">> config.sed
echo "s/^defines *=.*$/defines =/			">> config.sed
echo "s/mv -f make.new make/mv -f make.new.exe make.exe/">> config.sed

echo "s/cd glob; $(MAKE)/$(MAKE) -C glob/		">> config.sed

sed -e "s/^\"//" -e "s/\"$//" -e "s/[ 	]*$//" config.sed > config2.sed
sed -f config2.sed Makefile.in >> Makefile
del config.sed
del config2.sed

cd glob
call configure
cd ..
